import { HttpResponse, http } from 'msw';

/**
 * Intercept /fonts/{fontId}/{weight}.css requests and return @font-face CSS
 * that loads WOFF2 from the fontsource CDN. In a real Drydock instance these
 * files are generated by scripts/extract-fonts.mjs into ui/public/fonts/.
 */

const FONT_MAP: Record<string, { family: string; pkg: string }> = {
  'jetbrains-mono': { family: 'JetBrains Mono', pkg: '@fontsource/jetbrains-mono' },
  'source-code-pro': { family: 'Source Code Pro', pkg: '@fontsource/source-code-pro' },
  inconsolata: { family: 'Inconsolata', pkg: '@fontsource/inconsolata' },
  'commit-mono': { family: 'Commit Mono', pkg: '@fontsource/commit-mono' },
  'comic-mono': { family: 'Comic Mono', pkg: '@fontsource/comic-mono' },
};

export const fontHandlers = [
  http.get('/fonts/:fontId/:weightCss', ({ params }) => {
    const fontId = params.fontId as string;
    const weightCss = params.weightCss as string;
    const weight = weightCss.replace('.css', '');
    const font = FONT_MAP[fontId];

    if (!font) {
      return new HttpResponse(null, { status: 404 });
    }

    // Return CSS that uses the fontsource CDN
    const css = `@font-face {
  font-family: '${font.family}';
  font-style: normal;
  font-display: swap;
  font-weight: ${weight};
  src: url('https://cdn.jsdelivr.net/fontsource/fonts/${fontId}@latest/latin-${weight}-normal.woff2') format('woff2');
  unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0300-0301,U+0304,U+0306-0307,U+030A,U+030C,U+0312,U+0327,U+0331,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;
}`;

    return new HttpResponse(css, {
      headers: { 'Content-Type': 'text/css' },
    });
  }),
];
