const SELF_UPDATE_START_TIMEOUT_MS = 30_000;
const SELF_UPDATE_HEALTH_TIMEOUT_MS = 120_000;
const SELF_UPDATE_POLL_INTERVAL_MS = 1_000;

export {
  SELF_UPDATE_HEALTH_TIMEOUT_MS,
  SELF_UPDATE_POLL_INTERVAL_MS,
  SELF_UPDATE_START_TIMEOUT_MS,
};
