export const LOG_STREAM_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const LOG_STREAM_RATE_LIMIT_MAX = 1000;

export const WS_CLOSE_CODE_NORMAL = 1000;
export const WS_CLOSE_CODE_INTERNAL_ERROR = 1011;
export const WS_CLOSE_CODE_CONTAINER_NOT_RUNNING = 4001;
export const WS_CLOSE_CODE_CONTAINER_NOT_FOUND = 4004;
