import { daysToMs } from '../../model/maturity-policy.js';
import { toPositiveInteger } from '../../util/parse.js';

const CACHE_CONTROL_HEADER = 'public, max-age=31536000, immutable';
const FALLBACK_CACHE_CONTROL_HEADER = 'no-store';
const FALLBACK_ICON = 'fab fa-docker';
const FALLBACK_IMAGE_PROVIDER = 'selfhst';
const FALLBACK_IMAGE_SLUG = 'docker';
const MISSING_UPSTREAM_STATUS_CODES = new Set([403, 404]);

const DEFAULT_ICON_CACHE_TTL_MS = daysToMs(30);
const DEFAULT_ICON_CACHE_MAX_FILES = 5000;
const DEFAULT_ICON_CACHE_MAX_BYTES = 100 * 1024 * 1024;
const DEFAULT_ICON_CACHE_ENFORCEMENT_INTERVAL_MS = 10 * 1000;
const DEFAULT_ICON_IN_FLIGHT_TIMEOUT_MS = 15 * 1000;
const DEFAULT_ICON_PROXY_RATE_LIMIT_WINDOW_MS = 60 * 1000;
const DEFAULT_ICON_PROXY_RATE_LIMIT_MAX = 100;

const ICON_CACHE_TTL_MS = toPositiveInteger(
  process.env.DD_ICON_CACHE_TTL_MS,
  DEFAULT_ICON_CACHE_TTL_MS,
);
const ICON_CACHE_MAX_FILES = toPositiveInteger(
  process.env.DD_ICON_CACHE_MAX_FILES,
  DEFAULT_ICON_CACHE_MAX_FILES,
);
const ICON_CACHE_MAX_BYTES = toPositiveInteger(
  process.env.DD_ICON_CACHE_MAX_BYTES,
  DEFAULT_ICON_CACHE_MAX_BYTES,
);
const ICON_CACHE_ENFORCEMENT_INTERVAL_MS = toPositiveInteger(
  process.env.DD_ICON_CACHE_ENFORCEMENT_INTERVAL_MS,
  DEFAULT_ICON_CACHE_ENFORCEMENT_INTERVAL_MS,
);
const ICON_PROXY_RATE_LIMIT_WINDOW_MS = toPositiveInteger(
  process.env.DD_ICON_PROXY_RATE_LIMIT_WINDOW_MS,
  DEFAULT_ICON_PROXY_RATE_LIMIT_WINDOW_MS,
);
const ICON_PROXY_RATE_LIMIT_MAX = toPositiveInteger(
  process.env.DD_ICON_PROXY_RATE_LIMIT_MAX,
  DEFAULT_ICON_PROXY_RATE_LIMIT_MAX,
);

function getIconInFlightTimeoutMs() {
  return toPositiveInteger(
    process.env.DD_ICON_IN_FLIGHT_TIMEOUT_MS,
    DEFAULT_ICON_IN_FLIGHT_TIMEOUT_MS,
  );
}

export {
  CACHE_CONTROL_HEADER,
  FALLBACK_CACHE_CONTROL_HEADER,
  FALLBACK_ICON,
  FALLBACK_IMAGE_PROVIDER,
  FALLBACK_IMAGE_SLUG,
  getIconInFlightTimeoutMs,
  ICON_CACHE_ENFORCEMENT_INTERVAL_MS,
  ICON_CACHE_MAX_BYTES,
  ICON_CACHE_MAX_FILES,
  ICON_CACHE_TTL_MS,
  ICON_PROXY_RATE_LIMIT_MAX,
  ICON_PROXY_RATE_LIMIT_WINDOW_MS,
  MISSING_UPSTREAM_STATUS_CODES,
};
